name: e2e

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Run Cypress tests (Chrome)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config: baseUrl=https://www.demoblaze.com
        env:
          # Skip visual snapshotting on CI unless you set this true
          CYPRESS_VISUAL: "false"
